Update Convert-Kelee.yml

diff --git a/.github/workflows/Convert-Kelee.yml b/.github/workflows/Convert-Kelee.yml
--- a/.github/workflows/Convert-Kelee.yml
+++ b/.github/workflows/Convert-Kelee.yml
@@ -87,17 +87,17 @@ jobs:
 
           mkdir -p Modules/{Surge,Loon,Shadowrocket}/Kelee/Beta
 
-          for file in Modules/Loon/Kelee/Official/*.plugin; do
+          for file in Modules/Loon/Kelee/Official/*.lpx; do
             [ -f "$file" ] || continue
             filename=$(basename "$file")
             plugin_local_url="${plugin_base_url}${filename}"
-            Modules_name=$(basename "$plugin_local_url" .plugin)
+            Modules_name=$(basename "$plugin_local_url" .lpx)
             encoded_Modules_name=$(echo "$Modules_name" | jq -sRr @uri)
 
             Surge_url="http://localhost:9100/file/_start_/${plugin_local_url}/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=surge-module&category=${encoded_category}&nore=true"
             Surge_Beta_url="http://localhost:9101/file/_start_/${plugin_local_url}/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=surge-module&category=${encoded_category}&nore=true&jqEnabled=true"
-            Loon_url="http://localhost:9100/file/_start_/${plugin_local_url}/_end_/${encoded_Modules_name}.plugin?type=loon-plugin&target=loon-plugin&category=${encoded_category}&icon=Loon&nore=true"
-            Loon_Beta_url="http://localhost:9101/file/_start_/${plugin_local_url}/_end_/${encoded_Modules_name}.plugin?type=loon-plugin&target=loon-plugin&category=${encoded_category}&icon=Loon&nore=true&jqEnabled=true"
+            Loon_url="http://localhost:9100/file/_start_/${plugin_local_url}/_end_/${encoded_Modules_name}.lpx?type=loon-plugin&target=loon-plugin&category=${encoded_category}&icon=Loon&nore=true"
+            Loon_Beta_url="http://localhost:9101/file/_start_/${plugin_local_url}/_end_/${encoded_Modules_name}.lpx?type=loon-plugin&target=loon-plugin&category=${encoded_category}&icon=Loon&nore=true&jqEnabled=true"
             Shadowrocket_url="http://localhost:9100/file/_start_/${plugin_local_url}/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=shadowrocket-module&category=${encoded_category}&nore=true"
             Shadowrocket_Beta_url="http://localhost:9101/file/_start_/${plugin_local_url}/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=shadowrocket-module&category=${encoded_category}&nore=true&jqEnabled=true"
 
@@ -105,9 +105,9 @@ jobs:
             curl -A "Surge Mac/2985" -L -o "Modules/Surge/Kelee/${Modules_name}.sgmodule" "$Surge_url" || echo "Failed ${Modules_name}.sgmodule"
             curl -A "Surge Mac/2985" -L -o "Modules/Surge/Kelee/Beta/${Modules_name}.sgmodule" "$Surge_Beta_url" || echo "Failed ${Modules_name}.sgmodule"
             
-            echo "Converting to ${Modules_name}.plugin"
-            curl -A "Surge Mac/2985" -L -o "Modules/Loon/Kelee/${Modules_name}.plugin" "$Loon_url" || echo "Failed ${Modules_name}.plugin"
-            curl -A "Surge Mac/2985" -L -o "Modules/Loon/Kelee/Beta/${Modules_name}.plugin" "$Loon_Beta_url" || echo "Failed ${Modules_name}.plugin"
+            echo "Converting to ${Modules_name}.lpx"
+            curl -A "Surge Mac/2985" -L -o "Modules/Loon/Kelee/${Modules_name}.lpx" "$Loon_url" || echo "Failed ${Modules_name}.lpx"
+            curl -A "Surge Mac/2985" -L -o "Modules/Loon/Kelee/Beta/${Modules_name}.lpx" "$Loon_Beta_url" || echo "Failed ${Modules_name}.lpx"
             
             echo "Converting to ${Modules_name}.srmodule"
             curl -A "Surge Mac/2985" -L -o "Modules/Shadowrocket/Kelee/${Modules_name}.srmodule" "$Shadowrocket_url" || echo "Failed ${Modules_name}.srmodule"
