Update Copying-ddgksf2013.yml

diff --git a/.github/workflows/Copying-ddgksf2013.yml b/.github/workflows/Copying-ddgksf2013.yml
--- a/.github/workflows/Copying-ddgksf2013.yml
+++ b/.github/workflows/Copying-ddgksf2013.yml
@@ -61,8 +61,8 @@ jobs:
 
             Surge_url="http://localhost:9100/file/_start_/${plugin_url}/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=surge-module&category=${encoded_category}&nore=true"
             Surge_Beta_url="http://localhost:9101/file/_start_/${plugin_url/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=surge-module&category=${encoded_category}&nore=true&jqEnabled=true"
-            Loon_url="http://localhost:9100/file/_start_/${plugin_url}/_end_/${encoded_Modules_name}.plugin?type=loon-plugin&target=loon-plugin&category=${encoded_category}&icon=Loon&nore=true"
-            Loon_Beta_url="http://localhost:9101/file/_start_/${plugin_url}/_end_/${encoded_Modules_name}.plugin?type=loon-plugin&target=loon-plugin&category=${encoded_category}&icon=Loon&nore=true&jqEnabled=true"
+            Loon_url="http://localhost:9100/file/_start_/${plugin_url}/_end_/${encoded_Modules_name}.lpx?type=loon-plugin&target=loon-plugin&category=${encoded_category}&icon=Loon&nore=true"
+            Loon_Beta_url="http://localhost:9101/file/_start_/${plugin_url}/_end_/${encoded_Modules_name}.lpx?type=loon-plugin&target=loon-plugin&category=${encoded_category}&icon=Loon&nore=true&jqEnabled=true"
             Shadowrocket_url="http://localhost:9100/file/_start_/${plugin_url}/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=shadowrocket-module&category=${encoded_category}&nore=true"
             Shadowrocket_Beta_url="http://localhost:9101/file/_start_/${plugin_url}/_end_/${encoded_Modules_name}.sgmodule?type=loon-plugin&target=shadowrocket-module&category=${encoded_category}&nore=true&jqEnabled=true"
 
@@ -72,9 +72,9 @@ jobs:
             echo "Converting to ${Modules_name}.sgmodule"
             curl -A "Surge Mac/2985" -L -o "Modules/Surge/${Author}/${Modules_name}.sgmodule" "$Surge_url" || echo "Failed to download ${Modules_name}.sgmodule"
             curl -A "Surge Mac/2985" -L -o "Modules/Surge/${Author}/Beta/${Modules_name}.sgmodule" "$Surge_Beta_url" || echo "Failed to download ${Modules_name}.sgmodule"
-            echo "Converting to ${Modules_name}.plugin"
-            curl -A "Surge Mac/2985" -L -o "Modules/Loon/${Author}/${Modules_name}.plugin" "$Loon_url" || echo "Failed to download ${Modules_name}.lpx"
-            curl -A "Surge Mac/2985" -L -o "Modules/Loon/${Author}/Beta/${Modules_name}.lpx" "$Loon_Beta_url" || echo "Failed to download ${Modules_name}.plugin"
+            echo "Converting to ${Modules_name}.lpx"
+            curl -A "Surge Mac/2985" -L -o "Modules/Loon/${Author}/${Modules_name}.lpx" "$Loon_url" || echo "Failed to download ${Modules_name}.lpx"
+            curl -A "Surge Mac/2985" -L -o "Modules/Loon/${Author}/Beta/${Modules_name}.lpx" "$Loon_Beta_url" || echo "Failed to download ${Modules_name}.lpx"
             echo "Converting to $.srmodule"
             curl -A "Surge Mac/2985" -L -o "Modules/Shadowrocket/${Author}/${Modules_name}.srmodule" "$Shadowrocket_url" || echo "Failed to download ${Modules_name}.srmodule"
             curl -A "Surge Mac/2985" -L -o "Modules/Shadowrocket/${Author}/Beta/${Modules_name}.srmodule" "$Shadowrocket_Beta_url" || echo "Failed to download ${Modules_name}.srmodule"
